syntax on
filetype on
filetype plugin on
filetype indent on
scriptencoding utf-8
set encoding=utf-8
set mouse=a
set modeline
set nocompatible
set number
set relativenumber
set cursorline
set shiftwidth=4
set tabstop=4
set expandtab
set softtabstop=4
set nobackup
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set wildmenu
set wildmode=list:longest
set grepprg=grep\ -nH\ $*
set laststatus=2
set whichwrap=b,s,<,>,[,]
let g:loaded_powerline = 1 
let g:netrw_banner = 0
let g:netrw_liststyle = 3 
let g:netrw_winsize = 25
let g:netrw_browse_split = 4
let g:netrw_altv = 0
let g:netrw_alto = 1
let g:indent_guides_enable_on_vim_startup = 1
let g:indentLine_char = '│'
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
colorscheme habamax
highlight LineNr ctermfg=DarkGrey guifg=#666666
highlight CursorLineNr ctermfg=White guifg=#FFFFFF

" Map Ctrl+Arrow keys to switch tabs
nnoremap <C-Right> :tabnext<CR>
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-t> :tabnew<CR>
map <C-e> :Vexplore
map <C-x> :q
map <C-s> :w

" Automatically open the explorer when Vim starts
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END 
